# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2021-06-05T01:28:41+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Foo(BaseModel):
    required: int
    required_default: int = 2
    required_nullable: Optional[int] = Field(...)
    unrequired: Optional[int] = None
